# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zac/Documents/Code/sdl-tetris

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zac/Documents/Code/sdl-tetris

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zac/Documents/Code/sdl-tetris/CMakeFiles /home/zac/Documents/Code/sdl-tetris/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zac/Documents/Code/sdl-tetris/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tetris

# Build rule for target.
tetris: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tetris
.PHONY : tetris

# fast build rule for target.
tetris/fast:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/build
.PHONY : tetris/fast

src/board.o: src/board.cpp.o

.PHONY : src/board.o

# target to build an object file
src/board.cpp.o:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/board.cpp.o
.PHONY : src/board.cpp.o

src/board.i: src/board.cpp.i

.PHONY : src/board.i

# target to preprocess a source file
src/board.cpp.i:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/board.cpp.i
.PHONY : src/board.cpp.i

src/board.s: src/board.cpp.s

.PHONY : src/board.s

# target to generate assembly for a file
src/board.cpp.s:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/board.cpp.s
.PHONY : src/board.cpp.s

src/colour.o: src/colour.cpp.o

.PHONY : src/colour.o

# target to build an object file
src/colour.cpp.o:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/colour.cpp.o
.PHONY : src/colour.cpp.o

src/colour.i: src/colour.cpp.i

.PHONY : src/colour.i

# target to preprocess a source file
src/colour.cpp.i:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/colour.cpp.i
.PHONY : src/colour.cpp.i

src/colour.s: src/colour.cpp.s

.PHONY : src/colour.s

# target to generate assembly for a file
src/colour.cpp.s:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/colour.cpp.s
.PHONY : src/colour.cpp.s

src/dashboard.o: src/dashboard.cpp.o

.PHONY : src/dashboard.o

# target to build an object file
src/dashboard.cpp.o:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/dashboard.cpp.o
.PHONY : src/dashboard.cpp.o

src/dashboard.i: src/dashboard.cpp.i

.PHONY : src/dashboard.i

# target to preprocess a source file
src/dashboard.cpp.i:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/dashboard.cpp.i
.PHONY : src/dashboard.cpp.i

src/dashboard.s: src/dashboard.cpp.s

.PHONY : src/dashboard.s

# target to generate assembly for a file
src/dashboard.cpp.s:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/dashboard.cpp.s
.PHONY : src/dashboard.cpp.s

src/data.o: src/data.cpp.o

.PHONY : src/data.o

# target to build an object file
src/data.cpp.o:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/data.cpp.o
.PHONY : src/data.cpp.o

src/data.i: src/data.cpp.i

.PHONY : src/data.i

# target to preprocess a source file
src/data.cpp.i:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/data.cpp.i
.PHONY : src/data.cpp.i

src/data.s: src/data.cpp.s

.PHONY : src/data.s

# target to generate assembly for a file
src/data.cpp.s:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/data.cpp.s
.PHONY : src/data.cpp.s

src/holdStack.o: src/holdStack.cpp.o

.PHONY : src/holdStack.o

# target to build an object file
src/holdStack.cpp.o:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/holdStack.cpp.o
.PHONY : src/holdStack.cpp.o

src/holdStack.i: src/holdStack.cpp.i

.PHONY : src/holdStack.i

# target to preprocess a source file
src/holdStack.cpp.i:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/holdStack.cpp.i
.PHONY : src/holdStack.cpp.i

src/holdStack.s: src/holdStack.cpp.s

.PHONY : src/holdStack.s

# target to generate assembly for a file
src/holdStack.cpp.s:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/holdStack.cpp.s
.PHONY : src/holdStack.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/queue.o: src/queue.cpp.o

.PHONY : src/queue.o

# target to build an object file
src/queue.cpp.o:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/queue.cpp.o
.PHONY : src/queue.cpp.o

src/queue.i: src/queue.cpp.i

.PHONY : src/queue.i

# target to preprocess a source file
src/queue.cpp.i:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/queue.cpp.i
.PHONY : src/queue.cpp.i

src/queue.s: src/queue.cpp.s

.PHONY : src/queue.s

# target to generate assembly for a file
src/queue.cpp.s:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/queue.cpp.s
.PHONY : src/queue.cpp.s

src/tetromino.o: src/tetromino.cpp.o

.PHONY : src/tetromino.o

# target to build an object file
src/tetromino.cpp.o:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tetromino.cpp.o
.PHONY : src/tetromino.cpp.o

src/tetromino.i: src/tetromino.cpp.i

.PHONY : src/tetromino.i

# target to preprocess a source file
src/tetromino.cpp.i:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tetromino.cpp.i
.PHONY : src/tetromino.cpp.i

src/tetromino.s: src/tetromino.cpp.s

.PHONY : src/tetromino.s

# target to generate assembly for a file
src/tetromino.cpp.s:
	$(MAKE) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tetromino.cpp.s
.PHONY : src/tetromino.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... tetris"
	@echo "... edit_cache"
	@echo "... src/board.o"
	@echo "... src/board.i"
	@echo "... src/board.s"
	@echo "... src/colour.o"
	@echo "... src/colour.i"
	@echo "... src/colour.s"
	@echo "... src/dashboard.o"
	@echo "... src/dashboard.i"
	@echo "... src/dashboard.s"
	@echo "... src/data.o"
	@echo "... src/data.i"
	@echo "... src/data.s"
	@echo "... src/holdStack.o"
	@echo "... src/holdStack.i"
	@echo "... src/holdStack.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/queue.o"
	@echo "... src/queue.i"
	@echo "... src/queue.s"
	@echo "... src/tetromino.o"
	@echo "... src/tetromino.i"
	@echo "... src/tetromino.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

